import { BaseExecutor, type ExecuteInput, type ExecutorExecuteResult } from "./base.ts";
import { solveDeepSeekPowAsync } from "../lib/deepseek-pow.ts";
import { type OpenAIToolCall } from "../translator/webTools.ts";
import {
  serializeDeepSeekToolPrompt,
  parseDeepSeekToolCalls,
  buildToolConversationPrompt,
  extractUserQuery,
} from "../translator/deepseekWebTools.ts";
import { sanitizeErrorMessage } from "../utils/error.ts";
import {
  isThinkingModel,
  isSearchModel,
  formatStreamContent,
  appendSearchCitations,
  type DeepSeekSearchResult,
} from "./deepseek-web/stream-format.ts";
import {
  createFinishOnceGuard,
  createFinishedDrainScheduler,
} from "./deepseek-web-done-terminator.ts";
// LEV fork: WebSessionDriver for robust session management
import { WebSessionDriver } from "../services/webSessionDriver.ts";
import { DEEPSEEK_WEB_SESSION_CONFIG } from "./deepseek-web/sessionConfig.ts";
// LEV fork: token-aware budget utilities (Phase 4.3)
import {
  estimateTokens as estimateTextTokens,
  tokenAwareTruncate,
  getBudgetForProvider,
  FALLBACK_MAX_SYSTEM_CHARS,
  FALLBACK_MAX_CURRENT_MSG_CHARS,
} from "../services/tokenBudget.ts";
import { isBrowserAutomationEnabled } from "./base/browserAutomationFallback.ts";
import {
  acquireBrowserContext,
  openPage,
  type BrowserPoolContextOptions,
} from "../services/browserPool.ts";

type Page = import("playwright").Page;

export const DEEPSEEK_WEB_BASE = "https://chat.deepseek.com";
const DEEPSEEK_API_BASE = `${DEEPSEEK_WEB_BASE}/api`;
const COMPLETION_URL = `${DEEPSEEK_API_BASE}/v0/chat/completion`;

// Fingerprint headers the chat.deepseek.com web client sends on every /api/v0/*
// request. Kept in sync with a real captured completion request (client v2.0.0):
// the 2.0.0 web build DROPPED the legacy `X-App-Version` build stamp and ADDED
// `X-Client-Bundle-Id`. Sending the stale `X-App-Version` (and the old 1.8.0
// version) is itself a bot-detection signal, so match the current client exactly.
// NOTE: the live client also sends `x-hif-leim`, a signed client-attestation
// token generated by obfuscated JS. It is intentionally omitted — reproducing it
// requires porting that JS, and it is not currently enforced by the completion
// endpoint. Revisit if requests start failing a client-attestation check.
const FAKE_HEADERS: Record<string, string> = {
  Accept: "*/*",
  "Accept-Encoding": "gzip, deflate, br, zstd",
  "Accept-Language": "en-US,en;q=0.9",
  Origin: DEEPSEEK_WEB_BASE,
  Referer: `${DEEPSEEK_WEB_BASE}/`,
  "User-Agent":
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36",
  "X-Client-Bundle-Id": "com.deepseek.chat",
  "X-Client-Locale": "en-US",
  "X-Client-Platform": "web",
  "X-Client-Version": "2.0.0",
};

// ── Types ────────────────────────────────────────────────────────────────

interface PowChallenge {
  algorithm: string;
  challenge: string;
  salt: string;
  signature: string;
  difficulty: number;
  expire_at: number;
  expire_after: number;
  target_path: string;
}

interface TokenInfo {
  accessToken: string;
  expiresAt: number;
}

// ── Token cache (keyed by userToken → short-lived access token) ─────────

const tokenCache = new Map<string, TokenInfo>();
const sessionCache = new Map<string, { sessionId: string; createdAt: number }>();

const CACHE_MAX_SIZE = 100;

function evictOldest(cache: Map<string, unknown>): void {
  if (cache.size >= CACHE_MAX_SIZE) {
    const first = cache.keys().next().value;
    if (first) cache.delete(first);
  }
}

// ── Helpers ──────────────────────────────────────────────────────────────

export function extractUserToken(credentials: Record<string, unknown>): string | null {
  const raw = credentials?.apiKey || credentials?.accessToken;
  if (typeof raw !== "string" || raw.length === 0) return null;
  // Handle JSON-wrapped tokens (DeepSeek stores token as {"value":"..."})
  try {
    const parsed = JSON.parse(raw);
    if (typeof parsed?.value === "string") return parsed.value;
  } catch {
    // not JSON, use raw
  }
  return raw;
}

function errorResponse(status: number, message: string, dsCode?: number): Response {
  return new Response(
    JSON.stringify({
      error: { message, type: "upstream_error", code: dsCode ?? `HTTP_${status}` },
    }),
    { status, headers: { "Content-Type": "application/json" } }
  );
}

function resolveModelOptions(
  model?: string,
  bodyObj?: Record<string, unknown>
): {
  modelType: string;
  thinkingEnabled: boolean;
  searchEnabled: boolean;
} {
  const m = (model || "").toLowerCase();
  const modelType = m.includes("pro") || m.includes("expert") ? "expert" : "default";
  const thinkingEnabled =
    m.includes("r1") ||
    m.includes("think") ||
    m.includes("reason") ||
    bodyObj?.thinking_enabled === true ||
    bodyObj?.thinking === true ||
    !!bodyObj?.reasoning_effort;
  const searchEnabled =
    m.includes("search") ||
    bodyObj?.search_enabled === true ||
    bodyObj?.search === true ||
    bodyObj?.web_search === true;
  return { modelType, thinkingEnabled, searchEnabled };
}

function generateFakeCookie(): string {
  const ts = Date.now();
  const hex = (n: number) =>
    Array.from({ length: n }, () => Math.floor(Math.random() * 16).toString(16)).join("");
  const uid = () =>
    "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
      const r = (Math.random() * 16) | 0;
      return (c === "x" ? r : (r & 0x3) | 0x8).toString(16);
    });
  return `intercom-HWWAFSESTIME=${ts}; HWWAFSESID=${hex(18)}; Hm_lvt_${uid()}=${Math.floor(ts / 1000)}; _frid=${uid()}`;
}

// ── PoW Solver (DeepSeekHashV1) ─────────────────────────────────────────

async function solvePow(challenge: PowChallenge): Promise<string> {
  const answer = await solveDeepSeekPowAsync(
    challenge.algorithm,
    challenge.challenge,
    challenge.salt,
    challenge.difficulty,
    challenge.expire_at
  );
  if (answer < 0) throw new Error("PoW solver failed");
  return Buffer.from(
    JSON.stringify({
      algorithm: challenge.algorithm,
      challenge: challenge.challenge,
      salt: challenge.salt,
      answer,
      signature: challenge.signature,
      target_path: challenge.target_path,
    })
  ).toString("base64");
}

// ── SSE Transform (DeepSeek → OpenAI) ───────────────────────────────────

function transformSSE(deepseekStream: ReadableStream, model: string): ReadableStream {
  const encoder = new TextEncoder();
  const decoder = new TextDecoder();
  const streamModel = model || "deepseek-web";
  const id = `chatcmpl-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const created = Math.floor(Date.now() / 1000);
  let emittedRole = false;
  let currentPath: "thinking" | "content" | "" = "";
  const thinkingModel = isThinkingModel(streamModel);
  const searchResults: DeepSeekSearchResult[] = [];

  return new ReadableStream(
    {
      async start(controller) {
        const reader = deepseekStream.getReader();
        let buffer = "";

        const emit = (obj: object) => {
          controller.enqueue(encoder.encode(`data: ${JSON.stringify(obj)}\n\n`));
        };

        const chunk = (delta: object, finish?: string) => {
          emit({
            id,
            object: "chat.completion.chunk",
            created,
            model: streamModel,
            choices: [{ index: 0, delta, finish_reason: finish ?? null }],
          });
        };

        const ensureRole = () => {
          if (!emittedRole) {
            emittedRole = true;
            chunk({ role: "assistant", content: "" });
          }
        };

        const { finishOnce: finishStream, hasFinished } = createFinishOnceGuard(() => {
          const citations = appendSearchCitations(searchResults, streamModel);
          if (citations) {
            ensureRole();
            chunk({ content: `\n\n${citations}` });
          }
          ensureRole();
          chunk({}, "stop");
          // OpenAI-compatible clients (SDK, OpenCode) hang without this terminator.
          controller.enqueue(encoder.encode("data: [DONE]\n\n"));
          controller.close();
        });

        // LEV fork: Track whether any content has been emitted. DeepSeek
        // sometimes sends FINISHED prematurely before any content arrives,
        // causing a premature "stop" with 0 output tokens. If FINISHED
        // arrives with no content, extend the drain window instead of
        // closing immediately.
        let hasEmittedContent = false;

        // Do not close *immediately* on FINISHED — DeepSeek may still send
        // search_results afterward. Drain briefly, then always emit
        // stop + [DONE] so clients do not hang if the upstream body stays open.
        // LEV fork: use a longer initial drain (3s) when no content has been
        // emitted yet, to give the upstream time to deliver the actual response.
        const { scheduleFinishAfterDrain, clearFinishedDrain, isDrainPending } =
          createFinishedDrainScheduler(finishStream, hasEmittedContent ? undefined : 5000);

        const sendByPath = (raw: string) => {
          const text = formatStreamContent(raw, streamModel);
          if (!text) return;
          ensureRole();
          hasEmittedContent = true;
          let path = currentPath;
          if (!path && thinkingModel) path = "thinking";
          else if (!path && isSearchModel(streamModel)) path = "content";
          if (path === "thinking") {
            chunk({ reasoning_content: text });
          } else {
            chunk({ content: text });
          }
        };

        const applyFragmentType = (frag: any) => {
          const type = String(frag?.type || "").toUpperCase();
          if (type === "THINK") currentPath = "thinking";
          else if (type === "ANSWER" || type === "RESPONSE") currentPath = "content";
        };

        const handleFragment = (frag: any, setPathFromType = false) => {
          if (setPathFromType) applyFragmentType(frag);
          if (typeof frag?.content !== "string" || frag.content.length === 0) return;
          if (!setPathFromType) {
            const type = String(frag?.type || "").toUpperCase();
            if (type === "THINK") currentPath = "thinking";
            else if (type === "ANSWER" || type === "RESPONSE") currentPath = "content";
          }
          sendByPath(frag.content);
        };

        try {
          while (true) {
            const { done, value } = await reader.read();
            if (done) break;

            buffer += decoder.decode(value, { stream: true });
            const lines = buffer.split("\n");
            buffer = lines.pop() || "";

            for (const line of lines) {
              if (!line.startsWith("data: ") && !line.startsWith("data:")) continue;
              const payload = line.replace(/^data:\s*/, "").trim();

              if (payload === "[DONE]") {
                finishStream();
                return;
              }

              let data: Record<string, unknown>;
              try {
                data = JSON.parse(payload);
              } catch {
                continue;
              }

              const p = (data as any)?.p;
              const o = (data as any)?.o;
              const v = (data as any)?.v;

              if (v && typeof v === "object" && v.response) {
                if (v.response.thinking_enabled === true) currentPath = "thinking";
                else if (v.response.thinking_enabled === false) currentPath = "content";
                const fragments = v.response.fragments;
                if (Array.isArray(fragments)) {
                  for (const frag of fragments) handleFragment(frag, false);
                }
              }

              if (p === "response/fragments") {
                if (Array.isArray(v)) {
                  for (const frag of v) handleFragment(frag, true);
                } else if (v && typeof v === "object") {
                  handleFragment(v, true);
                }
              }

              if (p === "response" && Array.isArray(v)) {
                for (const entry of v) {
                  if (entry?.p === "response" && entry?.v?.thinking_enabled === true) {
                    currentPath = "thinking";
                  }
                }
              }

              if (p === "response/search_status") continue;

              if (p === "response/search_results" && Array.isArray(v)) {
                if (o !== "BATCH") {
                  searchResults.length = 0;
                  searchResults.push(...v);
                } else {
                  for (const op of v) {
                    const match = String(op?.p || "").match(/^(\d+)\/cite_index$/);
                    if (match) {
                      const index = parseInt(match[1], 10);
                      if (searchResults[index]) searchResults[index].cite_index = op.v;
                    }
                  }
                }
                continue;
              }

              if (typeof v === "string") {
                sendByPath(v);
              } else if (Array.isArray(v) && p === "response") {
                for (const entry of v) {
                  if (Array.isArray(entry?.v)) {
                    const joined = entry.v.map((item: any) => item?.content || "").join("");
                    if (joined) sendByPath(joined);
                  }
                }
              }

              if (p === "response/status" && v === "FINISHED") {
                scheduleFinishAfterDrain();
                continue;
              }

              // Any other post-FINISHED payload extends the drain window so we
              // still capture late search_results before closing.
              if (isDrainPending()) {
                scheduleFinishAfterDrain();
              }
            }
          }
        } catch (err) {
          clearFinishedDrain();
          if (!hasFinished()) {
            controller.error(err);
          }
          return;
        }

        finishStream();
      },
      cancel() {
        // Best-effort: cancel upstream reader if the client aborts mid-stream.
        // finishStream is not required here — the controller is already cancelled.
      },
    },
    { highWaterMark: 16384 }
  );
}

// LEV fork: Detect narrated tool intent — the model says it will use a tool
// ("Let me read X", "I'll check Y", "Let me continue reading") but then stops
// without emitting a <tool> block, killing the agent loop. This pattern is
// common with DeepSeek-web's text-based tool calling where the model narrates
// its plan but forgets to actually emit the structured tool block.
const NARRATED_INTENT_RE =
  /\b(let me|I'll|I will|I need to|let's|I want to|I'm going to)\b.+\b(read|check|look|search|find|continue|see|inspect|examine|explore|run|execute|call|use|open|list|grep|glob|write|edit|create|delete|shell|terminal)\b/i;

function looksLikeNarratedIntent(content: string): boolean {
  const text = content.trim();
  if (text.length < 10) return false;
  // Must not contain an actual tool block
  if (text.includes("<tool>")) return false;
  // For short content (< 500 chars), test the whole text.
  if (text.length <= 500) return NARRATED_INTENT_RE.test(text);
  // For long content, the model may write a lengthy analysis and then narrate
  // intent at the very end ("...Let me find the source file."). Check the last
  // ~400 chars (roughly 2-3 sentences) for the narrated-intent pattern. This
  // catches cases where the model produces a detailed diagnosis but then stops
  // without emitting a tool block.
  const tail = text.slice(-400);
  return NARRATED_INTENT_RE.test(tail);
}

// LEV fork: Synthesize a Grep tool call from narrated intent when the model
// says "I need to find..." but never emits a <tool> block. Extracted as a
// shared helper so both the direct-HTTP and browser-backed paths can use it.
function synthesizeGrepToolCall(
  lastUserText: string,
  requestedTools: unknown[]
): OpenAIToolCall | null {
  const hasGrep = requestedTools.some(
    (t) =>
      (t as { function?: { name?: string } })?.function?.name === "Grep" ||
      (t as { function?: { name?: string } })?.function?.name === "grep"
  );
  if (!hasGrep || !lastUserText) return null;
  const pageMatch = /\/(\w+)\/?$/.exec(lastUserText);
  const pattern = pageMatch
    ? pageMatch[1]
    : lastUserText
        .replace(/[<>\[\]{}]/g, "")
        .split(/\s+/)
        .filter(
          (w) =>
            w.length > 3 &&
            !/^(the|this|that|with|from|have|your|into|page|table|header|glass|seems|broken|aligned|look|need|find|code|unified|understand|issue|alignment|not|properly)$/i.test(
              w
            )
        )
        .slice(0, 3)
        .join("|");
  if (!pattern) return null;
  return {
    id: `call-${Date.now()}`,
    type: "function" as const,
    function: {
      name: "Grep",
      arguments: JSON.stringify({
        pattern,
        output_mode: "files_with_matches",
      }),
    },
  };
}

// LEV fork: Build the minimal corrective retry prompt for narrated-intent
// recovery. Shared between direct-HTTP and browser-backed paths.
function buildCorrectiveRetryPrompt(
  toolSystemPrompt: string,
  lastUserText: string,
  cleanedContent: string
): string {
  return (
    toolSystemPrompt +
    "\n\n---\nPrevious task context (last user request):\n" +
    tokenAwareTruncate(lastUserText, 2_000) +
    '\n\n---\nIMPORTANT: Your previous response was: "' +
    cleanedContent.slice(0, 200) +
    '" — you narrated intent to use a tool but did NOT emit a <tool> block. ' +
    "You MUST emit the <tool> block NOW. Do not describe what you will do — " +
    'do it by outputting the <tool>{"name": ..., "arguments": ..., "_nonce": ...}</tool> block immediately. ' +
    "For example, to find relevant files, emit: " +
    '<tool>{"name": "Grep", "arguments": {"pattern": "reposicion", "output_mode": "files_with_matches"}, "_nonce": "..."}</tool>'
  );
}

// LEV fork: Extract the last user message text from the messages array.
// Shared between direct-HTTP and browser-backed paths for narrated-intent recovery.
function extractLastUserText(messages: Array<{ role: string; content: string }>): string {
  const lastUserMsg = messages.filter((m) => m.role === "user").pop();
  if (!lastUserMsg) return "";
  const extractedQuery = extractUserQuery(lastUserMsg.content);
  if (extractedQuery) return extractedQuery;
  if (typeof lastUserMsg.content === "string") return lastUserMsg.content;
  if (Array.isArray(lastUserMsg.content)) {
    return (lastUserMsg.content as Array<{ type?: string; text?: string }>)
      .filter((p) => p?.type === "text")
      .map((p) => p?.text ?? "")
      .join("\n");
  }
  return "";
}

async function collectSSEContent(
  deepseekStream: ReadableStream,
  model: string
): Promise<{ content: string; reasoningContent: string }> {
  const decoder = new TextDecoder();
  const reader = deepseekStream.getReader();
  let buffer = "";
  let content = "";
  let reasoningContent = "";
  let currentPath: "thinking" | "content" | "" = "";
  const streamModel = model || "deepseek-web";
  const thinkingModel = isThinkingModel(streamModel);
  const searchResults: DeepSeekSearchResult[] = [];

  const appendByPath = (raw: string) => {
    const text = formatStreamContent(raw, streamModel);
    if (!text) return;
    let path = currentPath;
    if (!path && thinkingModel) path = "thinking";
    else if (!path && isSearchModel(streamModel)) path = "content";
    if (path === "thinking") reasoningContent += text;
    else content += text;
  };

  const applyFragmentType = (frag: any) => {
    const type = String(frag?.type || "").toUpperCase();
    if (type === "THINK") currentPath = "thinking";
    else if (type === "ANSWER" || type === "RESPONSE") currentPath = "content";
  };

  const handleFragment = (frag: any, setPathFromType = false) => {
    if (setPathFromType) applyFragmentType(frag);
    if (typeof frag?.content !== "string" || frag.content.length === 0) return;
    if (!setPathFromType) {
      const type = String(frag?.type || "").toUpperCase();
      if (type === "THINK") currentPath = "thinking";
      else if (type === "ANSWER" || type === "RESPONSE") currentPath = "content";
    }
    appendByPath(frag.content);
  };

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true });
    const lines = buffer.split("\n");
    buffer = lines.pop() || "";

    for (const line of lines) {
      if (!line.startsWith("data: ") && !line.startsWith("data:")) continue;
      const payload = line.replace(/^data:\s*/, "").trim();
      try {
        const data = JSON.parse(payload);
        const p = data?.p;
        const v = data?.v;

        if (v && typeof v === "object" && v.response) {
          if (v.response.thinking_enabled === true) currentPath = "thinking";
          else if (v.response.thinking_enabled === false) currentPath = "content";
          if (Array.isArray(v.response.fragments)) {
            for (const frag of v.response.fragments) handleFragment(frag, false);
          }
        }

        if (p === "response/fragments") {
          if (Array.isArray(v)) {
            for (const frag of v) handleFragment(frag, true);
          } else if (v && typeof v === "object") {
            handleFragment(v, true);
          }
        }

        if (p === "response" && Array.isArray(v)) {
          for (const entry of v) {
            if (entry?.p === "response" && entry?.v?.thinking_enabled === true) {
              currentPath = "thinking";
            }
          }
        }

        if (p === "response/search_status") continue;

        if (p === "response/search_results" && Array.isArray(v)) {
          if (data?.o !== "BATCH") {
            searchResults.length = 0;
            searchResults.push(...v);
          } else {
            for (const op of v) {
              const match = String(op?.p || "").match(/^(\d+)\/cite_index$/);
              if (match) {
                const index = parseInt(match[1], 10);
                if (searchResults[index]) searchResults[index].cite_index = op.v;
              }
            }
          }
          continue;
        }

        if (typeof v === "string") {
          appendByPath(v);
        } else if (Array.isArray(v) && p === "response") {
          for (const entry of v) {
            if (Array.isArray(entry?.v)) {
              const joined = entry.v.map((item: any) => item?.content || "").join("");
              if (joined) appendByPath(joined);
            }
          }
        }
      } catch {
        // skip
      }
    }
  }

  const citations = appendSearchCitations(searchResults, streamModel);
  if (citations) content += `\n\n${citations}`;

  return { content, reasoningContent };
}

// ── Prompt builder (DeepSeek native format, matches Chat2API) ────────────

function extractMessageText(content: unknown): string {
  if (Array.isArray(content)) {
    return (content as any[])
      .filter((item: any) => item.type === "text")
      .map((item: any) => item.text)
      .join("\n");
  }
  return String(content || "");
}

// #10527 — with no explicit `historyWindow`, genuinely multi-turn conversations (any
// assistant turn present, or more than one user turn) now auto-replay a bounded
// trajectory instead of only the last user message, so agentic clients that never send
// OpenAI-native `tools[]` (e.g. Cline, which embeds its own XML tool convention) don't
// silently lose the original task after a couple of tool-result turns. This cap keeps
// the auto-replay bounded for very long agent sessions; set `historyWindow` explicitly
// on the connection to raise or lower it.
const DEFAULT_AUTO_HISTORY_WINDOW = 20;

/**
 * Build the single prompt string the DeepSeek web API accepts.
 *
 * The web endpoint (`/api/v0/chat/completion`) takes only a `prompt` string, not a
 * `messages` array. For a genuinely single-turn request (one user message, no prior
 * assistant turns) we keep the minimal behavior — system prompt(s) + the last user
 * message only — which is fine for plain chat and avoids inflating token usage.
 *
 * For a multi-turn conversation, `historyWindow > 0` stitches the last N non-system
 * messages into a role-tagged transcript so agentic multi-turn clients keep context
 * across turns (rolling-window memory, #2942). With `historyWindow` unset/`<= 0` we now
 * auto-apply a bounded window (`DEFAULT_AUTO_HISTORY_WINDOW`) instead of dropping every
 * earlier turn (#10527) — the previous default silently discarded the original task
 * after a couple of turns for clients (Cline) that never send `tools[]`. The system
 * prompt(s) still lead the prompt and the newest user turn is the last line of the
 * transcript.
 */
export function messagesToPrompt(
  messages: Array<{ role: string; content: string; tool_call_id?: string; name?: string }>,
  historyWindow = 0
): string {
  if (messages.length === 0) return "";
  const systemParts: string[] = [];
  const conversation: Array<{ role: string; text: string }> = [];
  const callNameById = new Map<string, string>();
  let lastUserContent = "";
  for (const m of messages) {
    const text = extractMessageText(m.content).trim();
    if (m.role === "system") {
      if (text) systemParts.push(text);
    } else if (m.role === "user" || m.role === "assistant") {
      if (text) conversation.push({ role: m.role, text });
      if (m.role === "user") lastUserContent = text;
      const toolCalls = (m as { tool_calls?: unknown }).tool_calls;
      const calls = Array.isArray(toolCalls)
        ? (toolCalls as Array<{ id?: string; function?: { name?: string } }>)
        : [];
      for (const c of calls) {
        if (c?.id && typeof c.function?.name === "string") callNameById.set(c.id, c.function.name);
      }
    } else if (m.role === "tool") {
      // Tool results have no native slot in deepseek-web's single-prompt format. Without
      // this branch they were silently dropped (#4712) — the model never saw the tool
      // output and either re-called the tool endlessly or answered "I don't have that
      // information". Fold them into the transcript as plain text, mirroring the agentic
      // buildToolConversationPrompt() path.
      if (text) {
        const name = (m.tool_call_id && callNameById.get(m.tool_call_id)) || m.name || "tool";
        conversation.push({ role: "tool", text: `(${name}) ${text}` });
      }
    }
  }

  const parts: string[] = [];
  if (systemParts.length > 0) {
    let systemText = systemParts.join("\n\n");
    if (systemText.length > FALLBACK_MAX_SYSTEM_CHARS) {
      systemText = systemText.slice(0, FALLBACK_MAX_SYSTEM_CHARS) + "\n[...truncated...]";
    }
    parts.push(systemText);
  }

  const effectiveWindow =
    historyWindow > 0 ? historyWindow : conversation.length > 1 ? DEFAULT_AUTO_HISTORY_WINDOW : 0;

  if (effectiveWindow > 0 && conversation.length > 1) {
    // Rolling-window transcript of the most recent turns (#2942, auto-applied per
    // #10527 when no explicit historyWindow is configured and the conversation is
    // genuinely multi-turn).
    const recent = conversation.slice(-effectiveWindow);
    const transcript = recent
      .map((turn) =>
        turn.role === "assistant"
          ? `Assistant: ${turn.text}`
          : turn.role === "tool"
            ? `Tool result ${turn.text}`
            : `User: ${turn.text}`
      )
      .join("\n\n");
    parts.push(transcript);
  } else if (lastUserContent) {
    parts.push(lastUserContent);
  }

  return parts.join("\n\n").replace(/!\[.*?\]\(.*?\)/g, "");
}

// ── DeepSeek API calls (Bearer token auth, like Chat2API) ───────────────

async function acquireAccessToken(
  userToken: string,
  signal?: AbortSignal | null,
  log?: ExecuteInput["log"]
): Promise<string> {
  const cached = tokenCache.get(userToken);
  if (cached && cached.expiresAt > Math.floor(Date.now() / 1000)) {
    return cached.accessToken;
  }

  log?.info?.("DEEPSEEK-WEB", "Acquiring access token from /users/current...");
  const resp = await fetch(`${DEEPSEEK_API_BASE}/v0/users/current`, {
    headers: {
      Authorization: `Bearer ${userToken}`,
      ...FAKE_HEADERS,
    },
    signal: signal ?? undefined,
  });

  if (resp.status === 401 || resp.status === 403) {
    throw new Error("Token invalid or expired — get a new userToken from DeepSeek localStorage");
  }
  if (!resp.ok) {
    throw new Error(`users/current HTTP ${resp.status}`);
  }

  const json = await resp.json();
  if (json?.code && json.code !== 0) {
    const errMsg = json.msg || json?.data?.biz_msg || `error code ${json.code}`;
    tokenCache.delete(userToken);
    throw new Error(`DeepSeek rejected token: ${errMsg}`);
  }
  const bizData = json?.data?.biz_data || json?.biz_data;
  if (!bizData?.token) {
    const errMsg = json?.msg || json?.data?.biz_msg || "Unknown error";
    throw new Error(`Failed to acquire token: ${errMsg}`);
  }

  const accessToken = bizData.token;
  evictOldest(tokenCache);
  tokenCache.set(userToken, {
    accessToken,
    expiresAt: Math.floor(Date.now() / 1000) + 3600,
  });

  log?.info?.("DEEPSEEK-WEB", `Access token acquired (${accessToken.length} chars)`);
  return accessToken;
}

function parseDeepSeekErrorPayload(payload: unknown): { code?: number; message: string } | null {
  if (!payload || typeof payload !== "object") return null;
  const record = payload as Record<string, unknown>;
  const codeRaw = record.code;
  const code = typeof codeRaw === "number" ? codeRaw : undefined;
  const msg = record.msg;
  const data = record.data as Record<string, unknown> | undefined;
  const bizMsg = data?.biz_msg;
  const messageRaw = typeof msg === "string" ? msg : typeof bizMsg === "string" ? bizMsg : "";
  if (code !== undefined && code !== 0) {
    return { code, message: messageRaw || `DeepSeek error ${code}` };
  }
  return null;
}

async function createSession(accessToken: string, signal?: AbortSignal | null): Promise<string> {
  const resp = await fetch(`${DEEPSEEK_API_BASE}/v0/chat_session/create`, {
    method: "POST",
    headers: {
      ...FAKE_HEADERS,
      "Content-Type": "application/json",
      Authorization: `Bearer ${accessToken}`,
      Cookie: generateFakeCookie(),
    },
    body: JSON.stringify({}),
    signal: signal ?? undefined,
  });

  if (!resp.ok) throw new Error(`chat_session/create HTTP ${resp.status}`);
  const json = await resp.json();
  const bizData = json?.data?.biz_data || json?.biz_data;
  const id = bizData?.chat_session?.id;
  if (!id) throw new Error(`No session id: code=${json?.code}`);
  return id;
}

async function deleteSessionOnDeepSeek(accessToken: string, sessionId: string): Promise<void> {
  try {
    await fetch(`${DEEPSEEK_API_BASE}/v0/chat_session/delete`, {
      method: "POST",
      headers: {
        ...FAKE_HEADERS,
        "Content-Type": "application/json",
        Authorization: `Bearer ${accessToken}`,
      },
      body: JSON.stringify({ chat_session_id: sessionId }),
    });
  } catch {
    // best-effort cleanup
  }
}

function wrapStreamWithCleanup(
  responseStream: ReadableStream,
  cleanup: () => Promise<void>
): ReadableStream {
  const reader = responseStream.getReader();
  return new ReadableStream({
    async pull(controller) {
      const { done, value } = await reader.read();
      if (done) {
        controller.close();
        cleanup().catch(() => {});
        return;
      }
      controller.enqueue(value);
    },
    cancel() {
      reader.cancel();
      cleanup().catch(() => {});
    },
  });
}

async function getPowChallenge(
  accessToken: string,
  signal?: AbortSignal | null
): Promise<PowChallenge> {
  const resp = await fetch(`${DEEPSEEK_API_BASE}/v0/chat/create_pow_challenge`, {
    method: "POST",
    headers: {
      ...FAKE_HEADERS,
      "Content-Type": "application/json",
      Authorization: `Bearer ${accessToken}`,
    },
    body: JSON.stringify({ target_path: "/api/v0/chat/completion" }),
    signal: signal ?? undefined,
  });
  if (!resp.ok) throw new Error(`create_pow_challenge HTTP ${resp.status}`);
  const json = await resp.json();
  const bizData = json?.data?.biz_data || json?.biz_data;
  if (!bizData?.challenge?.challenge) throw new Error(`No PoW challenge: code=${json?.code}`);
  return bizData.challenge as PowChallenge;
}

// ── Tool-call response builder (#2820) ──────────────────────────────────

/**
 * Build the executor result for a tool-translated reply. Emits OpenAI `tool_calls`
 * with `finish_reason: "tool_calls"` when tool calls were parsed, otherwise plain
 * content. Supports both streaming (synthetic SSE) and non-streaming clients.
 */
function buildToolAwareResult(opts: {
  stream: boolean;
  clientModel: string;
  content: string;
  reasoningContent?: string;
  toolCalls: OpenAIToolCall[] | null;
  reqHeaders: Record<string, string>;
  requestPayload: unknown;
}) {
  const { stream, clientModel, content, reasoningContent, toolCalls, reqHeaders, requestPayload } =
    opts;
  const hasCalls = !!toolCalls && toolCalls.length > 0;
  const finishReason = hasCalls ? "tool_calls" : "stop";
  const id = `chatcmpl-${Date.now()}`;
  const created = Math.floor(Date.now() / 1000);

  if (stream) {
    const encoder = new TextEncoder();
    const emit = (
      controller: ReadableStreamDefaultController,
      delta: object,
      finish: string | null
    ) => {
      controller.enqueue(
        encoder.encode(
          `data: ${JSON.stringify({
            id,
            object: "chat.completion.chunk",
            created,
            model: clientModel,
            choices: [{ index: 0, delta, finish_reason: finish }],
          })}\n\n`
        )
      );
    };
    const sse = new ReadableStream({
      start(controller) {
        emit(controller, { role: "assistant", content: "" }, null);
        // Surrounding natural-language text (and reasoning) is emitted before the tool_calls
        // so a model reply that interleaves a plan with a call still reaches the client (#7).
        if (reasoningContent) emit(controller, { reasoning_content: reasoningContent }, null);
        // LEV fork: Empty-content watchdog. If both content and tool calls are
        // empty, DeepSeek returned nothing — likely because the prompt was too
        // large or the session expired. Emit an error message instead of a
        // silent empty response that kills the agent loop.
        if (!content && !hasCalls) {
          emit(
            controller,
            {
              content:
                "[DeepSeek error] Empty response from upstream — the prompt may be too large " +
                "or the session may be expired. Try reducing context or re-authenticating.",
            },
            null
          );
        }
        if (content) emit(controller, { content }, null);
        if (hasCalls) {
          emit(
            controller,
            {
              tool_calls: toolCalls!.map((tc, i) => ({
                index: i,
                id: tc.id,
                type: "function",
                function: { name: tc.function.name, arguments: tc.function.arguments },
              })),
            },
            null
          );
        }
        emit(controller, {}, finishReason);
        controller.enqueue(encoder.encode("data: [DONE]\n\n"));
        controller.close();
      },
    });
    return {
      response: new Response(sse, {
        status: 200,
        headers: { "Content-Type": "text/event-stream", "Cache-Control": "no-cache" },
      }),
      url: COMPLETION_URL,
      headers: reqHeaders,
      transformedBody: requestPayload,
    };
  }

  const message: Record<string, unknown> = { role: "assistant", content: content || "" };
  if (reasoningContent) message.reasoning_content = reasoningContent;
  if (hasCalls) {
    message.tool_calls = toolCalls;
    if (!content) message.content = null;
  } else if (!content) {
    // LEV fork: Empty-content watchdog for non-streaming tool path.
    message.content =
      "[DeepSeek error] Empty response from upstream — the prompt may be too large " +
      "or the session may be expired. Try reducing context or re-authenticating.";
  }
  const openaiResponse = {
    id,
    object: "chat.completion",
    created,
    model: clientModel,
    choices: [{ index: 0, message, finish_reason: finishReason }],
    usage: { prompt_tokens: 0, completion_tokens: 0, total_tokens: 0 },
  };
  return {
    response: new Response(JSON.stringify(openaiResponse), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    }),
    url: COMPLETION_URL,
    headers: reqHeaders,
    transformedBody: requestPayload,
  };
}

// ── Executor ─────────────────────────────────────────────────────────────

export class DeepSeekWebExecutor extends BaseExecutor {
  // LEV fork: WebSessionDriver for pre-dispatch validation and stream watchdog.
  private sessionDriver = new WebSessionDriver(DEEPSEEK_WEB_SESSION_CONFIG);

  constructor() {
    super("deepseek-web", { baseUrl: DEEPSEEK_WEB_BASE });
  }

  async testConnection(
    credentials: Record<string, unknown>,
    signal?: AbortSignal
  ): Promise<boolean> {
    try {
      const userToken = extractUserToken(credentials);
      if (!userToken) return false;
      const accessToken = await acquireAccessToken(userToken, signal);
      return !!accessToken;
    } catch {
      return false;
    }
  }

  private async executeViaBrowser(input: ExecuteInput): Promise<ExecutorExecuteResult | null> {
    if (!isBrowserAutomationEnabled()) return null;
    const { model, body, stream, credentials, signal, log } = input;
    const bodyObj = (body || {}) as Record<string, unknown>;
    const rawCreds = credentials as unknown as Record<string, unknown>;
    const userToken = extractUserToken(rawCreds);
    if (!userToken) return null;

    const messages = (Array.isArray(bodyObj.messages) ? bodyObj.messages : []) as Array<{
      role: string;
      content: string;
    }>;
    const { modelType, thinkingEnabled, searchEnabled } = resolveModelOptions(
      model as string,
      bodyObj
    );
    const psd = (rawCreds.providerSpecificData ?? {}) as Record<string, unknown>;
    const historyWindow =
      typeof psd.historyWindow === "number" && psd.historyWindow > 0 ? psd.historyWindow : 0;
    const requestedTools = bodyObj.tools;
    const hasTools = Array.isArray(requestedTools) && requestedTools.length > 0;
    const toolSystemPrompt = hasTools ? serializeDeepSeekToolPrompt(requestedTools) : "";
    const promptMessages = toolSystemPrompt
      ? [{ role: "system", content: toolSystemPrompt }, ...messages]
      : messages;
    let prompt = hasTools
      ? buildToolConversationPrompt(messages, toolSystemPrompt)
      : messagesToPrompt(promptMessages, historyWindow);

    const dsBudget = getBudgetForProvider("deepseek-web", model as string);
    const promptTokenEstimate = estimateTextTokens(prompt);
    if (promptTokenEstimate === 0 && prompt.length > FALLBACK_MAX_CURRENT_MSG_CHARS) {
      const charBudget = dsBudget.maxInputTokens * 4;
      prompt = prompt.slice(0, Math.max(1, charBudget)) + "\n[...truncated...]";
    } else if (promptTokenEstimate > dsBudget.maxInputTokens) {
      prompt = tokenAwareTruncate(prompt, dsBudget.maxInputTokens);
    }

    // LEV fork: Browser-backed API execution. Instead of filling a UI textarea
    // (which times out because DeepSeek uses a custom editor), we navigate to
    // chat.deepseek.com with the userToken cookie, then use page.evaluate() to
    // execute the full API flow (acquireToken → createSession → PoW → completion)
    // from within the browser context. This gives us:
    //   - Real browser fingerprint (Cloudflare/bot-detection bypass)
    //   - Proper cookie/origin headers
    //   - The PoW challenge solved in-browser (DeepSeek's JS may detect Node.js)
    //   - SSE response captured from the browser's fetch()
    const poolKey = `deepseek-web:${userToken.slice(0, 24)}`;
    const cookieString = `userToken=${userToken}`;
    const options: BrowserPoolContextOptions = {
      cookieDomain: "chat.deepseek.com",
      cookieString,
      warmupUrl: `${DEEPSEEK_WEB_BASE}/`,
    };

    let pooled;
    try {
      pooled = await acquireBrowserContext(poolKey, options);
    } catch (err) {
      log?.warn?.(
        "DEEPSEEK-WEB",
        `Browser automation: context acquire failed: ${sanitizeErrorMessage(err instanceof Error ? err.message : String(err))}`
      );
      return null;
    }

    let page: Page | null = null;
    try {
      if (signal?.aborted) throw new DOMException("Aborted", "AbortError");
      page = await openPage(pooled);
      await page.goto(`${DEEPSEEK_WEB_BASE}/`, { waitUntil: "domcontentloaded", timeout: 30_000 });
      await new Promise<void>((resolve, reject) => {
        if (signal?.aborted) return reject(new DOMException("Aborted", "AbortError"));
        const t = setTimeout(() => {
          signal?.removeEventListener("abort", onAbort);
          resolve();
        }, 2000);
        const onAbort = () => {
          clearTimeout(t);
          reject(new DOMException("Aborted", "AbortError"));
        };
        signal?.addEventListener("abort", onAbort, { once: true });
      });

      // Check if we hit a login wall
      const url = page.url();
      if (url.includes("/login") || url.includes("/auth")) {
        log?.warn?.("DEEPSEEK-WEB", "Browser automation: landed on login wall — session expired");
        return null;
      }

      // Execute the full DeepSeek API flow from within the browser context.
      // The browser's fetch() will automatically include cookies, origin, and
      // the correct fingerprint headers that DeepSeek's bot detection checks.
      const refFileIds = Array.isArray(bodyObj.ref_file_ids) ? bodyObj.ref_file_ids : [];

      log?.info?.(
        "DEEPSEEK-WEB",
        `Browser-backed API execution: model_type=${modelType}, thinking=${thinkingEnabled}, prompt_len=${prompt.length}`
      );

      // Phase 1: Acquire token, create session, get PoW challenge — all in the
      // browser context so requests carry real cookies, origin, and fingerprint.
      const phase1 = await page.evaluate(async (userToken: string) => {
        const API_BASE = "https://chat.deepseek.com/api";
        try {
          // Step 1: Acquire access token
          const tokenResp = await fetch(`${API_BASE}/v0/users/current`, {
            method: "GET",
            headers: {
              "Content-Type": "application/json",
              Authorization: `Bearer ${userToken}`,
            },
            credentials: "include",
          });
          if (!tokenResp.ok) return { error: `token_acquire_${tokenResp.status}` };
          const tokenJson = await tokenResp.json();
          const tokenBizData = tokenJson?.data?.biz_data || tokenJson?.biz_data;
          const accessToken = tokenBizData?.token;
          if (!accessToken)
            return { error: "no_access_token", tokenJson: JSON.stringify(tokenJson).slice(0, 200) };

          // Step 2: Create chat session
          const sessionResp = await fetch(`${API_BASE}/v0/chat_session/create`, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              Authorization: `Bearer ${accessToken}`,
            },
            credentials: "include",
            body: JSON.stringify({}),
          });
          if (!sessionResp.ok) return { error: `session_create_${sessionResp.status}` };
          const sessionJson = await sessionResp.json();
          const sessionBizData = sessionJson?.data?.biz_data || sessionJson?.biz_data;
          const sessionId = sessionBizData?.chat_session?.id;
          if (!sessionId)
            return {
              error: "no_session_id",
              sessionJson: JSON.stringify(sessionJson).slice(0, 200),
            };

          // Step 3: Get PoW challenge
          const powResp = await fetch(`${API_BASE}/v0/chat/create_pow_challenge`, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              Authorization: `Bearer ${accessToken}`,
            },
            credentials: "include",
            body: JSON.stringify({ target_path: "/api/v0/chat/completion" }),
          });
          if (!powResp.ok)
            return { error: `pow_challenge_${powResp.status}`, powStatus: powResp.status };
          const powJson = await powResp.json();
          const powBizData = powJson?.data?.biz_data || powJson?.biz_data;
          const challenge = powBizData?.challenge;
          if (!challenge)
            return { error: "no_pow_challenge", powJson: JSON.stringify(powJson).slice(0, 200) };

          return { error: null, accessToken, sessionId, challenge };
        } catch (e) {
          return { error: `phase1_exception: ${e instanceof Error ? e.message : String(e)}` };
        }
      }, userToken);

      if (!phase1 || phase1.error) {
        const diag = phase1
          ? JSON.stringify(
              Object.fromEntries(Object.entries(phase1).filter(([k]) => k !== "error"))
            ).slice(0, 300)
          : "null";
        log?.warn?.(
          "DEEPSEEK-WEB",
          `Browser-backed API phase1 failed: ${phase1?.error || "no result"} | diag: ${diag}`
        );
        return null;
      }

      // Phase 2: Solve PoW server-side using the proven solveDeepSeekPowAsync
      // solver, then send the completion request from within the browser.
      const powChallenge = phase1.challenge as PowChallenge;
      const powAnswer = await solvePow(powChallenge);

      // Phase 3: Send completion request from the browser with the PoW answer
      const completionPayload = {
        prompt,
        modelType,
        thinkingEnabled,
        searchEnabled,
        refFileIds,
        accessToken: phase1.accessToken,
        sessionId: phase1.sessionId,
        powAnswer,
      };

      const apiResult = await page.evaluate(async (payload) => {
        const COMPLETION_URL = "https://chat.deepseek.com/api/v0/chat/completion";

        const completionResp = await fetch(COMPLETION_URL, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${payload.accessToken}`,
            "X-Ds-Pow-Response": payload.powAnswer,
            "X-Client-Timezone-Offset": String(new Date().getTimezoneOffset() * -60),
          },
          credentials: "include",
          body: JSON.stringify({
            chat_session_id: payload.sessionId,
            parent_message_id: null,
            model_type: payload.modelType,
            prompt: payload.prompt,
            ref_file_ids: payload.refFileIds,
            thinking_enabled: payload.thinkingEnabled,
            search_enabled: payload.searchEnabled,
            preempt: false,
          }),
        });

        if (!completionResp.ok) {
          const errText = await completionResp.text().catch(() => "");
          return { error: `completion_${completionResp.status}`, body: errText };
        }

        // Read the full SSE response body
        const body = await completionResp.text();
        return { error: null, body, status: completionResp.status };
      }, completionPayload);

      if (!apiResult || apiResult.error) {
        log?.warn?.(
          "DEEPSEEK-WEB",
          `Browser-backed API failed: ${apiResult?.error || "no result"}`
        );
        return null;
      }

      log?.info?.(
        "DEEPSEEK-WEB",
        `Browser-backed API success: ${apiResult.body?.length || 0} bytes`
      );

      const clientModel = typeof model === "string" && model.trim() ? model.trim() : "deepseek-web";
      const upstreamStream = new ReadableStream<Uint8Array>({
        start(controller) {
          controller.enqueue(new TextEncoder().encode(apiResult.body));
          controller.close();
        },
      });

      if (hasTools) {
        let { content, reasoningContent } = await collectSSEContent(upstreamStream, clientModel);
        let { content: cleanedContent, toolCalls } = parseDeepSeekToolCalls(
          content,
          `call-${Date.now()}`,
          requestedTools
        );

        // LEV fork: Narrated-intent detector — same logic as direct HTTP path.
        // The model says "Let me read X" but stops without emitting a <tool>
        // block, killing the agent loop. Retry with a minimal corrective prompt
        // sent through the browser, then synthesize a Grep call if retry fails.
        if (
          (!toolCalls || toolCalls.length === 0) &&
          cleanedContent &&
          looksLikeNarratedIntent(cleanedContent)
        ) {
          log?.warn?.(
            "DEEPSEEK-WEB",
            "Browser path: narrated intent without tool block — retrying with minimal corrective prompt"
          );
          const lastUserText = extractLastUserText(messages);
          const minimalRetryPrompt = buildCorrectiveRetryPrompt(
            toolSystemPrompt,
            lastUserText,
            cleanedContent
          );

          // Retry through the browser: create a new session + PoW + completion
          try {
            const retryPhase1 = await page.evaluate(
              async (args: {
                userToken: string;
                retryPrompt: string;
                modelType: string;
                thinkingEnabled: boolean;
                searchEnabled: boolean;
              }) => {
                const API_BASE = "https://chat.deepseek.com/api";

                // Acquire access token
                const tokenResp = await fetch(`${API_BASE}/v0/users/current`, {
                  method: "GET",
                  headers: {
                    "Content-Type": "application/json",
                    Authorization: `Bearer ${args.userToken}`,
                  },
                  credentials: "include",
                });
                if (!tokenResp.ok) return { error: `token_${tokenResp.status}` };
                const tokenJson = await tokenResp.json();
                const tokenBizData = tokenJson?.data?.biz_data || tokenJson?.biz_data;
                const accessToken = tokenBizData?.token;
                if (!accessToken) return { error: "no_access_token" };

                // Create chat session
                const sessionResp = await fetch(`${API_BASE}/v0/chat_session/create`, {
                  method: "POST",
                  headers: {
                    "Content-Type": "application/json",
                    Authorization: `Bearer ${accessToken}`,
                  },
                  credentials: "include",
                  body: JSON.stringify({}),
                });
                if (!sessionResp.ok) return { error: `session_${sessionResp.status}` };
                const sessionJson = await sessionResp.json();
                const sessionBizData = sessionJson?.data?.biz_data || sessionJson?.biz_data;
                const sessionId = sessionBizData?.chat_session?.id;
                if (!sessionId) return { error: "no_session_id" };

                // Get PoW challenge
                const powResp = await fetch(`${API_BASE}/v0/chat/create_pow_challenge`, {
                  method: "POST",
                  headers: {
                    "Content-Type": "application/json",
                    Authorization: `Bearer ${accessToken}`,
                  },
                  credentials: "include",
                  body: JSON.stringify({ target_path: "/api/v0/chat/completion" }),
                });
                if (!powResp.ok) return { error: `pow_${powResp.status}` };
                const powJson = await powResp.json();
                const powBizData = powJson?.data?.biz_data || powJson?.biz_data;
                const challenge = powBizData?.challenge;
                if (!challenge) return { error: "no_pow_challenge" };

                return { error: null, accessToken, sessionId, challenge };
              },
              {
                userToken,
                retryPrompt: minimalRetryPrompt,
                modelType,
                thinkingEnabled,
                searchEnabled,
              }
            );

            if (retryPhase1 && !retryPhase1.error) {
              // Solve PoW server-side
              const retryPowChallenge = retryPhase1.challenge as PowChallenge;
              const retryPowAnswer = await solvePow(retryPowChallenge);

              // Send retry completion through the browser
              const retryResult = await page.evaluate(
                async (payload: {
                  accessToken: string;
                  sessionId: string;
                  powAnswer: string;
                  prompt: string;
                  modelType: string;
                  thinkingEnabled: boolean;
                  searchEnabled: boolean;
                }) => {
                  const COMPLETION_URL = "https://chat.deepseek.com/api/v0/chat/completion";
                  const resp = await fetch(COMPLETION_URL, {
                    method: "POST",
                    headers: {
                      "Content-Type": "application/json",
                      Authorization: `Bearer ${payload.accessToken}`,
                      "X-Ds-Pow-Response": payload.powAnswer,
                      "X-Client-Timezone-Offset": String(new Date().getTimezoneOffset() * -60),
                    },
                    credentials: "include",
                    body: JSON.stringify({
                      chat_session_id: payload.sessionId,
                      parent_message_id: null,
                      model_type: payload.modelType,
                      prompt: payload.prompt,
                      ref_file_ids: [],
                      thinking_enabled: payload.thinkingEnabled,
                      search_enabled: payload.searchEnabled,
                      preempt: false,
                    }),
                  });
                  if (!resp.ok) return { error: `completion_${resp.status}`, body: "" };
                  const body = await resp.text();
                  return { error: null, body };
                },
                {
                  accessToken: retryPhase1.accessToken,
                  sessionId: retryPhase1.sessionId,
                  powAnswer: retryPowAnswer,
                  prompt: minimalRetryPrompt,
                  modelType,
                  thinkingEnabled,
                  searchEnabled,
                }
              );

              if (retryResult && !retryResult.error) {
                const retryStream = new ReadableStream<Uint8Array>({
                  start(controller) {
                    controller.enqueue(new TextEncoder().encode(retryResult.body));
                    controller.close();
                  },
                });
                const retryContent = await collectSSEContent(retryStream, clientModel);
                const retryParsed = parseDeepSeekToolCalls(
                  retryContent.content,
                  `call-${Date.now()}`,
                  requestedTools
                );
                if (retryParsed.toolCalls && retryParsed.toolCalls.length > 0) {
                  content = retryContent.content;
                  reasoningContent = retryContent.reasoningContent;
                  cleanedContent = retryParsed.content;
                  toolCalls = retryParsed.toolCalls;
                  log?.info?.(
                    "DEEPSEEK-WEB",
                    "Browser path: narrated-intent retry succeeded — tool calls recovered"
                  );
                }
              }
            }
          } catch (retryErr) {
            log?.warn?.(
              "DEEPSEEK-WEB",
              `Browser path: narrated-intent retry failed: ${sanitizeErrorMessage(retryErr instanceof Error ? retryErr.message : String(retryErr))}`
            );
          }

          // LEV fork: If retry also failed, synthesize a Grep tool call
          if (!toolCalls || toolCalls.length === 0) {
            const lastUserText = extractLastUserText(messages);
            const synthCall = synthesizeGrepToolCall(lastUserText, requestedTools);
            if (synthCall) {
              log?.warn?.(
                "DEEPSEEK-WEB",
                `Browser path: synthesizing Grep tool call after narrated-intent retry failed`
              );
              toolCalls = [synthCall];
              cleanedContent = "";
            }
          }
        }

        return buildToolAwareResult({
          stream: stream !== false,
          clientModel,
          content: cleanedContent,
          reasoningContent,
          toolCalls,
          reqHeaders: { "X-OmniRoute-Transport": "browser" },
          requestPayload: { browser_backed: true, model_type: modelType, prompt },
        });
      }

      if (stream !== false) {
        const openaiStream = transformSSE(upstreamStream, clientModel);
        return {
          response: new Response(openaiStream, {
            status: 200,
            headers: { "Content-Type": "text/event-stream", "Cache-Control": "no-cache" },
          }),
          url: COMPLETION_URL,
          headers: { "X-OmniRoute-Transport": "browser" },
          transformedBody: { browser_backed: true, model_type: modelType, prompt },
        };
      }

      const { content, reasoningContent } = await collectSSEContent(upstreamStream, clientModel);
      const message: Record<string, string> = { role: "assistant", content };
      if (reasoningContent) message.reasoning_content = reasoningContent;
      const openaiResponse = {
        id: `chatcmpl-${Date.now()}`,
        object: "chat.completion",
        created: Math.floor(Date.now() / 1000),
        model: model || modelType,
        choices: [{ index: 0, message, finish_reason: "stop" }],
        usage: { prompt_tokens: 0, completion_tokens: 0, total_tokens: 0 },
      };
      return {
        response: new Response(JSON.stringify(openaiResponse), {
          status: 200,
          headers: { "Content-Type": "application/json" },
        }),
        url: COMPLETION_URL,
        headers: { "X-OmniRoute-Transport": "browser" },
        transformedBody: { browser_backed: true, model_type: modelType, prompt },
      };
    } catch (err) {
      if (err instanceof DOMException && err.name === "AbortError") throw err;
      log?.warn?.(
        "DEEPSEEK-WEB",
        `Browser automation failed: ${sanitizeErrorMessage(err instanceof Error ? err.message : String(err))}`
      );
      return null;
    } finally {
      try {
        if (page) await page.close();
      } catch {
        // ignore
      }
    }
  }

  async execute({ model, body, stream, credentials, signal, log }: ExecuteInput) {
    // LEV fork: Browser automation is the PRIMARY path. The browser executes
    // the full DeepSeek API flow (token → session → PoW → completion) via
    // page.evaluate(), giving us real browser fingerprint, proper cookies,
    // and in-browser PoW solving. Falls back to direct HTTP if browser fails.
    const browserResult = await this.executeViaBrowser({
      model,
      body,
      stream,
      credentials,
      signal,
      log,
    });
    if (browserResult) return browserResult;

    // Direct HTTP fallback (when browser automation is unavailable or fails)
    const directResult = await this.executeViaDirectHttp({
      model,
      body,
      stream,
      credentials,
      signal,
      log,
    });
    if (directResult) return directResult;

    // If both paths fail, return a generic error
    return {
      response: errorResponse(502, "DeepSeek-web: both browser automation and direct HTTP failed"),
      url: COMPLETION_URL,
      headers: {},
      transformedBody: body,
    };
  }

  private async executeViaDirectHttp({
    model,
    body,
    stream,
    credentials,
    signal,
    log,
  }: ExecuteInput): Promise<ExecutorExecuteResult | null> {
    const bodyObj = (body || {}) as Record<string, unknown>;

    // chat.deepseek.com's web API only accepts {prompt, ref_file_ids,
    // thinking_enabled, search_enabled} - no native tools field. Instead of failing
    // tool-using requests, translate them (#2820): serialize the OpenAI tools[] into a
    // <tool>...</tool> prompt contract on the way in, and parse the model's text reply
    // back into OpenAI tool_calls on the way out.
    const requestedTools = bodyObj.tools;
    const hasTools = Array.isArray(requestedTools) && requestedTools.length > 0;
    const toolSystemPrompt = hasTools ? serializeDeepSeekToolPrompt(requestedTools) : "";

    const messages = (Array.isArray(bodyObj.messages) ? bodyObj.messages : []) as Array<{
      role: string;
      content: string;
    }>;
    const promptMessages = toolSystemPrompt
      ? [{ role: "system", content: toolSystemPrompt }, ...messages]
      : messages;
    const rawCreds = credentials as unknown as Record<string, unknown>;

    const userToken = extractUserToken(rawCreds);
    if (!userToken) {
      return {
        response: errorResponse(
          400,
          "Invalid credentials: paste your userToken from DeepSeek localStorage " +
            "(DevTools → Application → Local Storage → chat.deepseek.com → userToken)"
        ),
        url: COMPLETION_URL,
        headers: {},
        transformedBody: body,
      };
    }

    // LEV fork: Pre-dispatch session validation.
    const connectionId = `deepseek-web-${userToken.slice(0, 12)}`;
    const sessionValid = await this.sessionDriver.validateSession(userToken, connectionId);
    if (!sessionValid) {
      return {
        response: errorResponse(
          503,
          "DeepSeek web session is expired or invalid. Re-authenticate via the dashboard."
        ),
        url: COMPLETION_URL,
        headers: {},
        transformedBody: body,
      };
    }

    const { modelType, thinkingEnabled, searchEnabled } = resolveModelOptions(
      model as string,
      bodyObj
    );

    // Per-connection memory config (#2942). Defaults preserve the legacy
    // fresh-session-per-request, last-user-message-only behavior.
    const psd = (rawCreds.providerSpecificData ?? {}) as Record<string, unknown>;
    const persistSession = psd.persistSession === true;
    const historyWindow =
      typeof psd.historyWindow === "number" && psd.historyWindow > 0 ? psd.historyWindow : 0;

    try {
      let t0 = Date.now();
      const accessToken = await acquireAccessToken(userToken, signal, log);
      log?.info?.("DEEPSEEK-WEB", `Token acquired in ${Date.now() - t0}ms`);

      // Tool (agentic) requests replay the whole trajectory — prior tool calls and their
      // results — so the model keeps context across turns instead of restarting each time.
      // Plain chat keeps the legacy last-user-message / rolling-window behavior.
      let prompt = hasTools
        ? buildToolConversationPrompt(messages, toolSystemPrompt)
        : messagesToPrompt(promptMessages, historyWindow);
      // LEV fork: token-aware prompt truncation (Phase 4.3)
      // DeepSeek-web has a ~32K token effective context window. Truncate the
      // prompt based on token estimates instead of raw character counts so CJK
      // content is handled correctly. Falls back to character-based budget if
      // token estimation fails.
      const dsBudget = getBudgetForProvider("deepseek-web", model as string);
      const promptTokenEstimate = estimateTextTokens(prompt);
      if (promptTokenEstimate === 0 && prompt.length > FALLBACK_MAX_CURRENT_MSG_CHARS) {
        const charBudget = dsBudget.maxInputTokens * 4;
        prompt = prompt.slice(0, Math.max(1, charBudget)) + "\n[...truncated...]";
        log?.info?.(
          "DEEPSEEK-WEB",
          `Character-based fallback truncation: ${prompt.length} chars (token estimate unavailable)`
        );
      } else if (promptTokenEstimate > dsBudget.maxInputTokens) {
        const truncatedPrompt = tokenAwareTruncate(prompt, dsBudget.maxInputTokens);
        log?.info?.(
          "DEEPSEEK-WEB",
          `Token-aware prompt truncation: ${promptTokenEstimate} → ${estimateTextTokens(truncatedPrompt)} tokens ` +
            `(budget ${dsBudget.maxInputTokens}, original ${prompt.length} chars)`
        );
        prompt = truncatedPrompt;
      }
      const refFileIds = Array.isArray(bodyObj.ref_file_ids) ? bodyObj.ref_file_ids : [];
      log?.info?.(
        "DEEPSEEK-WEB",
        `model_type=${modelType}, thinking=${thinkingEnabled}, search=${searchEnabled}, files=${refFileIds.length}, stream=${stream !== false}, persist=${persistSession}, window=${historyWindow}`
      );
      // LEV fork: diagnostic logging for prompt truncation debugging
      if (hasTools) {
        log?.info?.(
          "DEEPSEEK-WEB",
          `prompt_len=${prompt.length}, tool_sys_prompt_len=${toolSystemPrompt.length}, ` +
            `messages_count=${messages.length}, ` +
            `prompt_head_200=${JSON.stringify(prompt.slice(0, 200))}, ` +
            `has_user_query=${prompt.includes("User's actual request")}`
        );
      }

      // One completion attempt against a given session id (fresh PoW per attempt).
      const performCompletion = async (sid: string, customPrompt?: string) => {
        const powChallenge = await getPowChallenge(accessToken, signal);
        const powAnswer = await solvePow(powChallenge);
        const reqHeaders: Record<string, string> = {
          ...FAKE_HEADERS,
          "Content-Type": "application/json",
          Authorization: `Bearer ${accessToken}`,
          "X-Ds-Pow-Response": powAnswer,
          "X-Client-Timezone-Offset": String(new Date().getTimezoneOffset() * -60),
          Cookie: generateFakeCookie(),
        };
        const requestPayload = {
          chat_session_id: sid,
          parent_message_id: null,
          model_type: modelType,
          prompt: customPrompt ?? prompt,
          ref_file_ids: refFileIds,
          thinking_enabled: thinkingEnabled,
          search_enabled: searchEnabled,
          preempt: false,
        };
        const resp = await fetch(COMPLETION_URL, {
          method: "POST",
          headers: reqHeaders,
          body: JSON.stringify(requestPayload),
          signal: signal ?? undefined,
        });
        return { resp, reqHeaders, requestPayload };
      };

      // Acquire a session. With persistSession we reuse one upstream session per
      // userToken (rolling-window memory); otherwise we create a fresh one per
      // request (legacy behavior — dodges stale sessions when the user deletes
      // chats in the DeepSeek UI). (#2942)
      const acquireSession = async (): Promise<{ sessionId: string; reused: boolean }> => {
        if (persistSession) {
          const cached = sessionCache.get(userToken);
          if (cached) return { sessionId: cached.sessionId, reused: true };
          const created = await createSession(accessToken, signal);
          evictOldest(sessionCache);
          sessionCache.set(userToken, { sessionId: created, createdAt: Date.now() });
          return { sessionId: created, reused: false };
        }
        return { sessionId: await createSession(accessToken, signal), reused: false };
      };

      t0 = Date.now();
      let { sessionId, reused: reusedSession } = await acquireSession();
      log?.info?.(
        "DEEPSEEK-WEB",
        `Session ${reusedSession ? "reused" : "created"} in ${Date.now() - t0}ms`
      );

      t0 = Date.now();
      log?.info?.("DEEPSEEK-WEB", `POST ${COMPLETION_URL}`);
      let { resp, reqHeaders, requestPayload } = await performCompletion(sessionId);
      log?.info?.(
        "DEEPSEEK-WEB",
        `Completion response in ${Date.now() - t0}ms, status=${resp.status}`
      );

      // A reused session that fails is likely stale (user deleted the chat in the
      // DeepSeek UI). Drop it, create a fresh session, and retry once. (#2942)
      if (!resp.ok && persistSession && reusedSession) {
        log?.warn?.("DEEPSEEK-WEB", "Reused session failed — retrying with a fresh session");
        sessionCache.delete(userToken);
        sessionId = await createSession(accessToken, signal);
        evictOldest(sessionCache);
        sessionCache.set(userToken, { sessionId, createdAt: Date.now() });
        reusedSession = false;
        ({ resp, reqHeaders, requestPayload } = await performCompletion(sessionId));
      }

      if (!resp.ok) {
        const status = resp.status;
        let errMsg = `DeepSeek API error (${status})`;
        if (status === 401 || status === 403) {
          tokenCache.delete(userToken);
          errMsg = "DeepSeek token expired — get a fresh userToken from localStorage.";
        } else if (status === 429) {
          errMsg = "DeepSeek rate limited. Wait and retry.";
        }
        log?.warn?.("DEEPSEEK-WEB", errMsg);

        try {
          const errBody = await resp.json();
          if (errBody?.code && errBody.code !== 0) {
            errMsg = `DeepSeek error ${errBody.code}: ${errBody.msg}`;
          }
        } catch {
          /* ignore */
        }

        if (persistSession) sessionCache.delete(userToken);
        deleteSessionOnDeepSeek(accessToken, sessionId).catch(() => {});
        return {
          response: errorResponse(status, errMsg),
          url: COMPLETION_URL,
          headers: reqHeaders,
          transformedBody: requestPayload,
        };
      }

      // Check for HTTP 200 with DeepSeek error JSON
      const ct = resp.headers.get("content-type") || "";
      if (ct.includes("application/json")) {
        try {
          const json = await resp.json();
          const parsed = parseDeepSeekErrorPayload(json);
          if (parsed) {
            const errMsg = `DeepSeek error ${parsed.code}: ${parsed.message}`;
            log?.warn?.("DEEPSEEK-WEB", errMsg);
            const status = parsed.code === 40003 ? 401 : parsed.code === 40002 ? 429 : 502;
            if (parsed.code === 40003) {
              tokenCache.delete(userToken);
            }
            if (persistSession) sessionCache.delete(userToken);
            deleteSessionOnDeepSeek(accessToken, sessionId).catch(() => {});
            return {
              response: errorResponse(status, errMsg, parsed.code),
              url: COMPLETION_URL,
              headers: reqHeaders,
              transformedBody: requestPayload,
            };
          }
          if (!persistSession) deleteSessionOnDeepSeek(accessToken, sessionId).catch(() => {});
          return {
            response: new Response(JSON.stringify(json), {
              status: 200,
              headers: { "Content-Type": "application/json" },
            }),
            url: COMPLETION_URL,
            headers: reqHeaders,
            transformedBody: requestPayload,
          };
        } catch {
          /* not JSON, continue */
        }
      }

      // Persistent sessions are kept across requests for reuse; only delete the
      // upstream chat session when persistence is off (legacy behavior). (#2942)
      const cleanupFn = persistSession
        ? async () => {}
        : () => deleteSessionOnDeepSeek(accessToken, sessionId);

      const clientModel = typeof model === "string" && model.trim() ? model.trim() : "deepseek-web";

      // Tool-call translation: buffer the full reply and parse <tool> blocks into
      // OpenAI tool_calls. Buffering (even for stream clients) is acceptable because
      // tool invocations are short and need the complete block to parse. (#2820)
      if (hasTools) {
        if (!resp.body) {
          await cleanupFn();
          return {
            response: errorResponse(502, "DeepSeek-web returned no response body"),
            url: COMPLETION_URL,
          };
        }
        let { content, reasoningContent } = await collectSSEContent(resp.body, clientModel);
        await cleanupFn();
        let { content: cleanedContent, toolCalls } = parseDeepSeekToolCalls(
          content,
          `call-${Date.now()}`,
          requestedTools
        );

        // LEV fork: Narrated-intent detector. The model sometimes says "Let me
        // read X" or "I'll check Y" and then stops without emitting a <tool>
        // block — killing the agent loop because no tool actually runs. When
        // we detect this pattern (content with intent phrases but no tool
        // calls), retry once with a MINIMAL corrective prompt — not the full
        // original prompt, which may already be near DeepSeek's token limit.
        // Appending to the full prompt would push it over the edge and produce
        // another empty response. Instead, we build a compact prompt that
        // includes just the tool contract, the last user request, and the
        // corrective instruction.
        if (
          (!toolCalls || toolCalls.length === 0) &&
          cleanedContent &&
          looksLikeNarratedIntent(cleanedContent)
        ) {
          log?.warn?.(
            "DEEPSEEK-WEB",
            "Narrated intent without tool block — retrying with minimal corrective prompt"
          );
          const retrySession = await createSession(accessToken, signal);
          const lastUserText = extractLastUserText(messages);
          const minimalRetryPrompt = buildCorrectiveRetryPrompt(
            toolSystemPrompt,
            lastUserText,
            cleanedContent
          );
          const retryResp = await performCompletion(retrySession, minimalRetryPrompt);
          deleteSessionOnDeepSeek(accessToken, retrySession).catch(() => {});
          if (retryResp.resp.ok) {
            if (!retryResp.resp.body) {
              return {
                response: errorResponse(502, "DeepSeek-web retry returned no response body"),
                url: COMPLETION_URL,
              };
            }
            const retryResult = await collectSSEContent(retryResp.resp.body, clientModel);
            const retryParsed = parseDeepSeekToolCalls(
              retryResult.content,
              `call-${Date.now()}`,
              requestedTools
            );
            if (retryParsed.toolCalls && retryParsed.toolCalls.length > 0) {
              content = retryResult.content;
              reasoningContent = retryResult.reasoningContent;
              cleanedContent = retryParsed.content;
              toolCalls = retryParsed.toolCalls;
              reqHeaders = retryResp.reqHeaders;
              requestPayload = retryResp.requestPayload;
            }
          }
          // LEV fork: If the retry ALSO failed (no tool calls), synthesize a
          // Grep tool call from the narrated intent to keep the agent loop
          // alive. The model said "I need to find..." — give it a search.
          if (!toolCalls || toolCalls.length === 0) {
            const synthCall = synthesizeGrepToolCall(lastUserText, requestedTools);
            if (synthCall) {
              log?.warn?.(
                "DEEPSEEK-WEB",
                `Narrated intent retry also failed — synthesizing Grep tool call`
              );
              toolCalls = [synthCall];
              cleanedContent = "";
            }
          }
        }

        return buildToolAwareResult({
          stream: stream !== false,
          clientModel,
          content: cleanedContent,
          reasoningContent,
          toolCalls,
          reqHeaders,
          requestPayload,
        });
      }

      if (stream !== false) {
        if (!resp.body) {
          await cleanupFn();
          return {
            response: errorResponse(502, "DeepSeek-web returned no response body for streaming"),
            url: COMPLETION_URL,
          };
        }
        const openaiStream = transformSSE(resp.body, clientModel);
        const wrappedStream = wrapStreamWithCleanup(openaiStream, cleanupFn);
        return {
          response: new Response(wrappedStream, {
            status: 200,
            headers: { "Content-Type": "text/event-stream", "Cache-Control": "no-cache" },
          }),
          url: COMPLETION_URL,
          headers: reqHeaders,
          transformedBody: requestPayload,
        };
      }

      if (!resp.body) {
        await cleanupFn();
        return {
          response: errorResponse(502, "DeepSeek-web returned no response body for non-streaming"),
          url: COMPLETION_URL,
        };
      }
      const { content, reasoningContent } = await collectSSEContent(resp.body, clientModel);
      await cleanupFn();
      const message: Record<string, string> = { role: "assistant", content };
      if (reasoningContent) message.reasoning_content = reasoningContent;
      const openaiResponse = {
        id: `chatcmpl-${Date.now()}`,
        object: "chat.completion",
        created: Math.floor(Date.now() / 1000),
        model: model || modelType,
        choices: [
          {
            index: 0,
            message,
            finish_reason: "stop",
          },
        ],
        usage: { prompt_tokens: 0, completion_tokens: 0, total_tokens: 0 },
      };
      return {
        response: new Response(JSON.stringify(openaiResponse), {
          status: 200,
          headers: { "Content-Type": "application/json" },
        }),
        url: COMPLETION_URL,
        headers: reqHeaders,
        transformedBody: requestPayload,
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      log?.error?.("DEEPSEEK-WEB", `Direct HTTP failed: ${msg}`);

      if (err instanceof DOMException && err.name === "AbortError") {
        return {
          response: errorResponse(499, "Request cancelled"),
          url: COMPLETION_URL,
          headers: {},
          transformedBody: body,
        };
      }

      // Return null to allow browser automation fallback for unexpected errors
      return null;
    }
  }
}

export const deepseekWebExecutor = new DeepSeekWebExecutor();

// Re-export for auto-refresh executor and tests
export { acquireAccessToken, tokenCache, sessionCache };
